language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - npm install codecov.io coveralls request lerna@2.0.0-rc.4
script:
  - cd packages/fexp-js
  - npm install
  - cd -
  - cd packages/fexp-js-lang
  - npm install
  - cd -
  - cd packages/fexp-js-lang-gis
  - npm install
  - cd -
  - pwd
  - npm run test

after_success:
  - npm run coverage:combine
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
